spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lending_dev
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    # 'validate' checks if the schema matches the entities at startup, which is safer than 'update'.
    # Use 'update' only if you want Hibernate to automatically alter tables during development.
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    # On a dev machine, you might want to clean and migrate on startup for a fresh database state.
    # Consider activating a 'clean' profile for this: spring.flyway.clean-on-validation-error=true
    locations: classpath:db/migration

# Development-focused logging settings.
logging:
  level:
    org.springframework.jdbc.core: DEBUG # Useful for debugging raw JDBC operations.
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"