spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/lending_test}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
  flyway:
    enabled: false

server:
  port: ${SERVER_PORT:8081}

logging:
  level:
    root: INFO
    "[org.springframework.web]": DEBUG
