spring:
  profiles:
    active: dev

  application:
    name: lending-backend

management:
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    root: INFO
    "[org.springframework.web]": INFO
    "[org.hibernate.SQL]": DEBUG
    "[org.hibernate.type.descriptor.sql.BasicBinder]": TRACE
