spring:
  datasource:
    # The Testcontainers JDBC URL simplifies setup. Environment variables provide flexibility.
    url: ${TEST_DB_URL:jdbc:tc:postgresql:15.2:///testdb}
    username: ${TEST_DB_USERNAME:test}
    password: ${TEST_DB_PASSWORD:test}
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    hikari:
      maximum-pool-size: 5

  jpa:
    # 'validate' is appropriate for tests to ensure migrations and entities are in sync.
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration

  # Disable Spring Security's default user for tests unless specifically needed.
  security:
    user:
      name: test-user
      password: test-password

# Configuration for Testcontainers
testcontainers:
  # Reusing containers can speed up test execution significantly.
  reuse:
    enabled: true

# Logging levels suitable for a test environment.
logging:
  level:
    org.testcontainers: INFO
    com.lending.backend: DEBUG

server:
  port: ${SERVER_PORT:8081}