spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/lending_dev}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        "[format_sql]": true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

# Logging configuration
logging:
  level:
    root: INFO
    com.lending: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG
  file:
    name: logs/application.log
    max-size: 50MB
    max-history: 30
    total-size-cap: 1GB
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

server:
  port: ${SERVER_PORT:8080}
